<?php

namespace Database\Factories;

use App\Enums\RoomType;
use App\Models\Laboratory;
use App\Models\Room;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Room>
 */
class RoomFactory extends Factory
{
    public function definition(): array
    {
        return [
            'code' => 'TEST-'.strtoupper(fake()->unique()->bothify('??-###')),
            'name' => 'Test Room '.fake()->unique()->numerify('####'),
            'type' => RoomType::Classroom,
            'capacity' => fake()->numberBetween(20, 100),
            'location' => 'Test Location '.fake()->numerify('###'),
            'description' => 'Test-only room generated by RoomFactory.',
            'is_active' => true,
            'owning_laboratory_id' => null,
        ];
    }

    public function classroom(): static
    {
        return $this->state(fn () => [
            'type' => RoomType::Classroom,
            'owning_laboratory_id' => null,
        ]);
    }

    public function laboratory(Laboratory $laboratory): static
    {
        return $this->state(fn () => [
            'type' => RoomType::Laboratory,
            'owning_laboratory_id' => $laboratory->id,
        ]);
    }
}
